In [11]:
%matplotlib widget
import spectral as spy
import spectral.io.envi as envi

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import japanize_matplotlib

from PIL import Image
import csv
import mplcursors

from scipy.signal import argrelmax

In [12]:
HDR_PATH_1 = '../data/iphone_808080_1_2023-07-12_002/results/REFLECTANCE_2023-07-12_002.hdr'
HDR_PATH_2 = '../data/iphone_808080_2_2023-07-12_003/results/REFLECTANCE_2023-07-12_003.hdr'
HDR_PATH_3 = '../data/iphone_808080_3_2023-07-12_004/results/REFLECTANCE_2023-07-12_004.hdr'
HDR_PATH_4 = '../data/iphone_808080_4_2023-07-24_005/results/REFLECTANCE_2023-07-24_005.hdr'
HDR_PATH_5 = '../data/iphone_808080_5_2023-07-24_007/results/REFLECTANCE_iphone_808080_2023-07-24_007.hdr'

IMG_PATH_1 = '../data/iphone_808080_1_2023-07-12_002/results/REFLECTANCE_2023-07-12_002.png'
IMG_PATH_2 = '../data/iphone_808080_2_2023-07-12_003/results/REFLECTANCE_2023-07-12_003.png'
IMG_PATH_3 = '../data/iphone_808080_3_2023-07-12_004/results/REFLECTANCE_2023-07-12_004.png'
IMG_PATH_4 = '../data/iphone_808080_4_2023-07-24_005/results/REFLECTANCE_2023-07-24_005.png'
IMG_PATH_5 = '../data/iphone_808080_5_2023-07-24_007/results/REFLECTANCE_iphone_808080_2023-07-24_007.png'

hdr_paths = [HDR_PATH_1,HDR_PATH_2,HDR_PATH_3,HDR_PATH_4,HDR_PATH_5]
img_paths = [IMG_PATH_1,IMG_PATH_2,IMG_PATH_3,IMG_PATH_4,IMG_PATH_5]

In [13]:
spec_imgs = []
for path in hdr_paths:
    spec_imgs.append(envi.open(path))

In [14]:
wave_lengthes = []
hdr = envi.read_envi_header(HDR_PATH_1)

for wl in hdr['wavelength']:
    wave_lengthes.append(float(wl))

In [15]:
pixel_x = 225 # X座標
pixel_y = 225  # Y座標

y = []
for spec_img in spec_imgs:
    y.append(spec_img.read_pixel(512-pixel_x,pixel_y)[:121])

for elem in y:
    print(argrelmax(elem,order=3))

(array([ 20,  44,  77, 101]),)
(array([ 20,  44,  77, 100]),)
(array([20, 44, 78]),)
(array([19, 43, 78]),)
(array([19, 44, 78]),)
